######################################################################
# Automatically generated by qmake (3.0) dim. juin 12 03:13:21 2016
######################################################################

TEMPLATE = app
QT += gui declarative
TARGET = Billiard
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h ParamArea.h ShapeFunctions.h SpaceArea.h
SOURCES += main.cpp MainWindow.cpp ParamArea.cpp ShapeFunctions.cpp SpaceArea.cpp
